admin/urls.py
from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
	url(r'^$','admin.views.index', name='index'),
	url(r'^login$', 'admin.views.admin_login', name='login'),
	url(r'^logout$', 'admin.views.admin_logout', name='logout'),
	url(r'^registro', include('register.urls')),
	url(r'^matriculas', include('enrollment.urls')),
	url(r'^recursos',include('custom.urls')),
	url(r'^pensum',include('pensum.urls')),
	url(r'^control',include('control.urls')),
	url(r'^configuracion$','admin.views.configuracion', name='configuracion'),
	url(r'^reportes',include('report.urls')),
	url(r'^boletin$','admin.views.boletin', name='boletin'),
	url(r'^buscarBoletin$','admin.views.buscarBoletin', name='buscarBoletin'),
	url(r'^crearBoletin$','admin.views.crearBoletin', name='crearBoletin'),
	url(r'^usoPlataforma$','admin.views.usoPlataforma', name='usoPlataforma'),
	url(r'^buscarEstadistica$','admin.views.buscarEstadistica', name='buscarEstadistica'),
	url(r'^/logros$','admin.views.logros', name='logros'),
	url(r'^/actividades$','admin.views.actividades', name='actividades'),
	url(r'^/indicadores$','admin.views.indicadores', name='indicadores'),
	url(r'^/asistencia$','admin.views.asistencia', name='asistencia'),
	url(r'^/observador$','admin.views.observador', name='observador'),
	url(r'^/herramienta$','admin.views.herramienta', name='herramienta'),
	url(r'^/api$','admin.views.api', name='api'),

)

appSchool/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import static
from django.conf import settings

urlpatterns = patterns('',
	url(r'^back/', include('admin.urls')),
	url(r'^plataform/', include('front.urls')),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

front/urls.py
from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
	url(r'^$','front.views.front', name='front'),
	url(r'^login$', 'admin.views.admin_login', name='login'),
	url(r'^logout$', 'admin.views.admin_logout', name='logout'),
	url(r'^fromMenu$', 'front.views.fromMenu', name='fromMenu'),
	url(r'^fromHerramienta$', 'front.views.fromHerramienta', name='fromHerramienta'),
	url(r'^fromNotas$', 'front.views.fromNotas', name='fromNotas'),
	url(r'^Logros$', 'front.views.Logros', name='Logros'),
	url(r'^actividades$', 'front.views.actividades', name='actividades'),
	url(r'^saveActividad$', 'front.views.saveActividad', name='saveActividad'),
	url(r'^foros$','front.views.foros',name='foros'),
	url(r'^observaciones$', 'front.views.observaciones', name='observaciones'),
	url(r'^wikis$', 'front.views.wikis', name='wikis'),
	url(r'^paginawiki$', 'front.views.paginawiki', name='paginawiki'),
	url(r'^formPaginaWiki$', 'front.views.formPaginaWiki', name='formPaginaWiki'),
	url(r'^saveFormPaginaWiki$', 'front.views.saveFormPaginaWiki', name='saveFormPaginaWiki'),
	url(r'^NotaActividad$', 'front.views.NotaActividad', name='NotaActividad'),
	url(r'^fromNota$', 'front.views.fromNota', name='fromNota'),

)

front/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from register.models import Cursos
from pensum.models import *

class Envio(models.Model):

    def get_upload_path(self, filename):
		url = "files/users/%s/%s" % (self.id_estudiante.id, filename)
		return url


    id_estudiante = models.ForeignKey(User, db_column='ID_ESTUDIANTE')
    id_actividad = models.ForeignKey(Actividad, db_column='ID_ACTIVIDAD') # Field name made lowercase.
    adjunto = models.FileField(upload_to=get_upload_path, blank=True, null=True)



    class Meta:
        db_table=u'Envio'

pensum/models.py
from django.contrib.auth.models import User
from django.db import models
from register.models import Cursos
from filebrowser.fields import FileBrowseField



class Materia(models.Model):
    id_cursos = models.ForeignKey(Cursos, db_column='ID_CURSOS') # Field name made lowercase.
    id_docente = models.ForeignKey(User, db_column='ID_USER')
    nombre_materia = models.CharField(max_length=600, db_column='NOMBRE_MATERIA') # Field name made lowercase.
    fecha_inicio = models.DateField(db_column='FECHA_INICIO') # Field name made lowercase.
    estado_materia = models.BooleanField(default=True, db_column='ESTADO_MATERIA')
    descripcion_materia = models.CharField(max_length=600, db_column='DESCRIPCION_MATERIA')


    
    class Meta:
        db_table = u'Materia'

class Logro(models.Model):
    id_materia = models.ForeignKey(Materia, db_column='ID_MATERIA') # Field name made lowercase.
    nombre_logro = models.CharField(max_length=600, db_column='NOMBRE_LOGRO') # Field name made lowercase.
    descripcion_logro = models.CharField(max_length=600, db_column='DESCRIPCION') # Field name made lowercase.
    


    
    class Meta:
        db_table = u'Logro'

class Actividad(models.Model):

    id_logro = models.ForeignKey(Logro, db_column='ID_LOGRO') # Field name made lowercase.
    nombre_actividad = models.CharField(max_length=600, db_column='NOMBRE_ACTIVIDAD') # Field name made lowercase.
    descripcion_actividad = models.CharField(max_length=3000, db_column='DESCRIPCION_ACTIVIDAD') # Field name made lowercase.
    fecha_inicio = models.DateField(db_column='FECHA_INICIO')
    fecha_fin = models.DateField(db_column='FECHA_FIN')
    estado_envio=models.BooleanField(default=True, db_column='ESTADO_ENVIO')
    actividad_externa = models.BooleanField(default=False)
    paquete = models.FileField(upload_to='packages/zipped/', null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.id:
            super(Actividad, self).save(*args, **kwargs)
        
        if self.actividad_externa:
            path = extract_package(str(self.id), self.paquete)
            Actividad.objects.filter(id=self.id).update(descripcion_actividad="<a href='/%s/'>Ir a la actividad</a>" % (path))



    class Meta:
        db_table = u'Actividad'

class Indicador(models.Model):
    id_actividad = models.ForeignKey(Actividad, db_column='ID_ACTIVIDAD') # Field name made lowercase.
    nombre_indicador = models.CharField(max_length=600, db_column='NOMBRE_INDICADOR') # Field name made lowercase.
    descripcion_indicador = models.CharField(max_length=600, db_column='DESCRIPCION_INDICADOR') # Field name made lowercase.
    

    
    class Meta:
        db_table = u'Indicador'

class Nota(models.Model):
    id_actividad = models.ForeignKey(Actividad, db_column='ID_ACTIVIDAD') # Field name made lowercase.
    nota=models.DecimalField(max_digits=3,decimal_places=2,db_column='NOTA')
    id_estudiante = models.ForeignKey(User, db_column='ID_ESTUDIANTE')



    class Meta:
        db_table= u'Nota'


import zipfile
import shutil
import os      

def extract_package(path, package):
    #File to unzip
    path = os.path.join('packages', path)

    zfile = zipfile.ZipFile(package)

    #Delete target directory
    
    try:
        shutil.rmtree(path)
    except Exception, e:
        pass

    #Make target directory
    os.makedirs(path)
    #Unzip
    zfile.extractall(path)

    path = path + "/" + os.path.basename(package.name)
    path = path.replace('.zip', '')

    return path

front/views.py
from django.shortcuts import render_to_response, redirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.admin.models import LogEntry
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib import messages
from register.models import Cursos
from pensum.models import *
from front.models import *
from control.models import *
from custom.models import *


@login_required(login_url='login')
def front(request):
	dat=request.user.grado
	cursos = None
	materias = None

	try:
		cursos=Cursos.objects.get(nombre_curso=dat)
		materias=Materia.objects.filter(id_cursos=cursos.id)
	except Cursos.DoesNotExist:
		pass
	rol=request.user.rol
	print rol+"no"
	if rol != 'estudiante':
		print rol
		return render_to_response('examples/500.html',context_instance=RequestContext(request))

	data={'materias':materias}
	return render_to_response('front/front.html',data,context_instance=RequestContext(request))

def fromMenu(request):
	curso=request.POST.get('uid')
	materia=None
	logros=None
	herramientas=None
	user=None
	estudiante=None
	nota=None
	try:
		materia=Materia.objects.get(id=curso)
		logros=Logro.objects.filter(id_materia=materia)
		log=len(logros)
		herramientas=Wiki.objects.filter(id_materia=materia)
		herr=len(herramientas)
		user=request.user.id
		estudiante=User.objects.get(id=user)
		nota=Nota.objects.filter(id_estudiante=estudiante)
		n= len(nota)

	except Materia.DoesNotExist:
		pass

	data={'curso':curso,'materia':materia,'log':log,'herr':herr,'n':n}
	return render_to_response('front/pages/front/cursos.html', data,context_instance=RequestContext(request))

def fromHerramienta(request):
	mate=request.POST.get('materia')
	materia=Materia.objects.get(id=mate)
	data={'materia':materia}
	return render_to_response('front/pages/front/Herramientas.html',data, context_instance=RequestContext(request))

def fromNotas(request):
	return render_to_response('front/pages/front/Notas.html', context_instance=RequestContext(request))

def Logros(request):
	mate=request.POST.get('materia')
	materia=Materia.objects.get(id=mate)
	logro=Logro.objects.filter(id_materia=materia)
	data={'logro':logro,'materia':materia}
	return render_to_response('front/pages/front/Logros.html', data, context_instance=RequestContext(request))	

def actividades(request):
	if 'logro' in request.POST:
		log=request.POST.get('logro')
	else:
		log=request.session.get('logro')
		del request.session['logro']

	logro=Logro.objects.get(id=log)
	id_user=request.user.id
	usuario=User.objects.get(id=id_user)
	ids=Envio.objects.filter(id_estudiante=usuario).values('id_actividad')
	not_user=Nota.objects.filter(id_estudiante=usuario).values('id_actividad')

	filtered=Actividad.objects.filter(id_logro=logro.id).exclude(id__in=ids)
	try:
		actividad = filtered.exclude(id__in=not_user)
	except Nota.DoesNotExist:
		actividad=filtered
	
		
	data={'actividad':actividad}
	return render_to_response('front/pages/front/Actividades.html', data,context_instance=RequestContext(request))

def saveActividad(request):

	uid=request.POST.get('uid')
	actividad=Actividad.objects.get(id=uid)
	id_user=request.user.id
	usuario=User.objects.get(id=id_user)

	nuevo_envio = Envio.objects.create(id_estudiante=usuario,id_actividad=actividad)


	if request.FILES:
		nuevo_envio.adjunto = request.FILES.get('adjunto')

	nuevo_envio.save()


	request.session['logro']=actividad.id_logro.id

	return redirect(reverse('actividades'))

def foros(request):
	return render_to_response('front/pages/front/Foros.html', data,context_instance=RequestContext(request))

def wikis(request):
	mate=request.POST.get('materia')
	materia=Materia.objects.get(id=mate)
	wiki=Wiki.objects.filter(id_materia=materia)
	data={'wiki':wiki}
	return render_to_response('front/pages/front/Wikis.html', data, context_instance=RequestContext(request))


def observaciones(request):
	est=request.user.id
	obs=Observacion.objects.filter(id_estudiante=est)
	data={'obs':obs}
	return render_to_response('front/pages/front/Observaciones.html', data, context_instance=RequestContext(request))

def paginawiki(request):
	if 'uid' in request.POST:
		uid=request.POST.get('uid')
		print "ERROR"+uid
	else:
		uid=request.session.get('uid')
		del request.session['uid']
	wiki=Wiki.objects.get(id=uid)
	try:
		paginaWikis=PaginaWiki.objects.filter(id_wiki=wiki)
	except PaginaWiki.DoesNotExist:
		paginaWikis=None
	data={'paginaWikis':paginaWikis,'wiki':wiki}
	return render_to_response('front/pages/front/paginawiki.html', data, context_instance=RequestContext(request))

def formPaginaWiki(request):
	uid=request.POST.get("uid")
	wiki=Wiki.objects.get(id=uid)
	data={'wiki':wiki}
	return render_to_response('front/pages/front/CrearPaginaWiki.html',data,context_instance=RequestContext(request))

def saveFormPaginaWiki(request):
	id_wiki=request.POST.get("uid")
	wiki=Wiki.objects.get(id=id_wiki)
	descripcion=request.POST.get('narrativa')
	user_id=request.user.id
	user=User.objects.get(id=user_id)
	paginawiki=PaginaWiki.objects.create(id_wiki=wiki,aporte=descripcion,id_estudiante=user)
	request.session['uid']=id_wiki
	return redirect(reverse('paginawiki'))

def NotaActividad(request):
	user=request.user.id
	estudiante=User.objects.get(id=user)
	nota=request.GET.get('nota')
	uid_act=request.GET.get('uid_act')
	actividad=Actividad.objects.get(id=uid_act)
	nota=Nota.objects.create(id_actividad=actividad,nota=nota,id_estudiante=estudiante)

	code = 'La nota ha sido registrada, <a href="'+reverse('front')+'">Volver a inicio</a>'

	return HttpResponse(code)

def fromNota(request):
	mate=request.POST.get('materia')
	materia=Materia.objects.get(id=mate)
	logros=Logro.objects.filter(id=materia.id)

	all_activities = None
	
	for logro in logros:
		if all_activities:
			all_activities = all_activities + logro.actividad_set.all()
		else:
			all_activities = logro.actividad_set.all()


	

	data={'all_activities':all_activities}
	return render_to_response('front/pages/front/NotaPorMateria.html',data, context_instance=RequestContext(request))

admin/templates/front/pages/front/NotaPorMateria.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title> we-learning</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
         <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" />
        <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
        <link rel="stylesheet" href="{% static "css/ionicons.min.css" %}">
        <link rel="stylesheet" href="{% static "css/morris/morris.css" %}" />
        <link rel="stylesheet" href="{% static "css/jvectormap/jquery-jvectormap-1.2.2.css" %}">
        <link rel="stylesheet" href="{% static "css/fullcalendar/fullcalendar.css" %}">
        <link rel="stylesheet" href="{% static "css/daterangepicker/daterangepicker-bs3.css" %}" />
        <link rel="stylesheet" href="{% static "css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" %}">
        <link rel="stylesheet" href="{% static "css/AdminLTE_fig.css" %}">
  

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
   </head>
    <body class="skin-blue">
        <!-- header logo: style can be found in header.less -->
        <header class="header">
            <a href="../plataform/" class="logo">
                <!-- Add the class icon to your logo image or logo icon to add the margining -->
               <img src="{% static "img/v-learning100.png" %}"  alt="User Image" />

            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="glyphicon glyphicon-user"></i>
                                <span>{{ request.user.username }}<i class="caret"></i></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header bg-light-blue">
                                    <img src="{% static "img/avatar5.png" %}" class="img-circle" alt="User Image" />
                                    <p>
                                        {{ request.user.username }} - {{request.user.rol}}
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                     <!--   <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Perfil</a>
                                    </div>-->
                                    <div class="pull-right">
                                        <a href="logout" class="btn btn-default btn-flat">Cerrar Sesión</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- Sidebar user panel -->
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src="{% static "img/avatar5.png" %}"  class="img-circle" alt="User Image" />
                        </div>
                        <div class="pull-left info">
                            <p>Hola, {{ request.user.username }}</p>

                            <a href="#"><i class="fa fa-circle text-success"></i>Online</a>
                        </div>
                    </div>
                    <!-- search form -->
                   
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <ul class="sidebar-menu">
                        
                        <li>
                            <a href="../plataform/">
                                <i class="ion-clipboard"></i> <span>Materias</span>
                            </a>
                        </li>
                        <li  class="active">
                            <a href="observaciones">
                                <i class="ion-ios7-eye"></i> <span>Observaciones</span>
                            </a>
                        </li>
                    </ul>
                        </li>
                    </ul>
                </section>
                <!-- /.sidebar -->
            </aside>

            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        <small>Observaciones</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i>Inicio</a></li>
                        <li class="active">Observaciones</li>
                    </ol>
                </section>

           <!-- Main content -->
                <section class="content">
                 <div class="row">
                        <!-- left column -->
                        <div class="col-md-8">
                            
                            <!-- general form elements -->
                        <div class="row">
                        <div class="col-xs-12">
                            <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Calificar</h3>
                                   
                                    <div class="box-tools">
                                        
                                    </div>
                                </div><!-- /.box-header -->
                                <div class="box-body table-responsive no-padding">
                                    
                                    <table class="table table-hover">
                                        <tr>
                                            <th>Nombre Usuario</th>
                                            <th>Nombre actividad</th>
                                            <th>Nota</th>
                                        </tr>
                                <form class="input-group" role="form" action="notExterna" method="POST">
                                    {%for activity in all_activities%}

                                        {% for note in activity.nota_set.all %}
                                        
                                        {% if note.id_estudiante.id == request.user.id %}
                                       
                                       <tr>
                                        <input name="ui-not" type="hidden" value={{nota.id}}>
                                  
                                        <td name="materia">{{note.id_estudiante.username}}</td>
                                        <td>{{note.id_actividad.nombre_actividad}}</td>
                                         <td>
                                           {{note.nota}}
                                        </td>
                                                {% csrf_token %}
                                                                                    
                                       
                                        
                                    </tr>
                                         {% endif %}
                                                                                    
                                      {% endfor %}

                                    {%endfor%} 

                                    </table>
                                      <div class="box-footer">
                                        <button type="submit" class="btn btn-primary">Recargar</button>
                                    </div>   
                                    </form>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div>
                    </div>
                            
                </section><!-- /.content -->     
        </div><!-- ./wrapper -->
        <!-- jQuery 2.0.2 -->
        <script src='{% static "js/jquery.min.js" %}'></script>
        <!-- jQuery UI 1.10.3 -->
        <script src='{% static "js/jquery-ui-1.10.3.min.js" %}'></script>
        <!-- Bootstrap -->
        <script src='{% static "js/bootstrap.min.js" %}'></script>
        <!-- Morris.js charts -->
        <script src='{% static "js/plugins/morris/morris.min.js" %}'></script>
        <!-- Sparkline -->
        <script src='{% static "js/plugins/sparkline/jquery.sparkline.min.js" %}'></script>
        <!-- jvectormap -->
        <script src='{% static "js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" %}'></script>
        <script src='{% static "js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js" %}'></script>
        <!-- fullCalendar -->
        <script src='{% static "js/plugins/fullcalendar/fullcalendar.min.js" %}'></script>
        <!-- jQuery Knob Chart -->
        <script src='{% static "js/plugins/jqueryKnob/jquery.knob.js" %}'></script>
        <!-- daterangepicker -->
        <script src='{% static "js/plugins/daterangepicker/daterangepicker.js" %}'></script>
        <!-- Bootstrap WYSIHTML5 -->
        <script src='{% static "js/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" %}'></script>
        <!-- iCheck -->
        <script src='{% static "js/plugins/iCheck/icheck.min.js" %}'></script>
        <!-- AdminLTE App -->
        <script src='{% static "js/AdminLTE/app.js" %}'></script>
        <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
        <script src='{% static "js/AdminLTE/dashboard.js" %}'></script>
        <!-- AdminLTE for demo purposes -->
        <script src='{% static "js/AdminLTE/demo.js" %}'></script>

    </body>
</html>